Add beacon block reward endpoint
attestantio/go-eth2-client pull request #162
Opened 2024-09-20 14:45 UTC by MisiakGeo

Add Block Rewards `/eth/v1/beacon/rewards/blocks` endpoint, now supp

2024-09-20 14:57 UTC, MisiakGeo commented
Ignore the events.go (It was fixed by @mcdee). It is still working perfectly without errors, but `urlForCall` function is considered better.

2024-09-21 17:10 UTC, mcdee requested changes
Thanks for this PR, a few comments inline.  Also, please could you add in `api/v1/beaconblockreward_yaml.go` and `api/v1/beaconblockreward_test.go` files to add YAML support and tests for the spec, respectively?  The tests in particular are important to keep up coverage rates for the library.

2024-09-21 17:10 UTC, mcdee commented on http/beaconblockreward.go
> +// BeaconBlockHeader provides the block header given the opts.
Please could you fix this comment to match the function.

2024-09-21 17:10 UTC, mcdee commented on api/v1/beaconblockreward.go
> +// BeaconBlockReward Rewards info for a single block
Please can you fix comments so that they end in a period?  Thanks.

2024-09-21 17:10 UTC, mcdee commented on api/v1/beaconblockreward.go
> +	ProposerIndex uint64
This should be of type `phase0.ValidatorIndex`

2024-09-21 17:10 UTC, mcdee commented on api/v1/beaconblockreward.go
> +	Total uint64
This and other gwei values should be of type `phase0.Gwei`

2024-09-21 17:10 UTC, mcdee commented on http/events.go
> +	"net/url"
Please can you revert the changes to this file, as they have been addressed elsewhere.

2024-09-21 18:03 UTC, MisiakGeo commented
@mcdee Thank you very for the comments. I will take a look. A comment from my side. YAML files can be found in `api/v1/daneb/*_yaml.go` . Should I place them in `api/v1`?

2024-09-21 18:15 UTC, mcdee commented
Sorry, after taking another look it appears that the rewards object is not a spec object, so it doesn't need the YAML piece.

2025-01-04 00:27 UTC, mcdee commented
Superseded by 8910181b413ea0d482141be8d5440cd01c37349f

2025-01-04 00:27 UTC, closed without merging