add builder spec validator registration structs to the v1 package
attestantio/go-eth2-client pull request #19
Opened 2022-07-18 08:59 UTC by ciaranmcveigh5

2022-07-19 21:42 UTC, mcdee requested changes
Thank you for your submission.  A few items that need tweaking, but nothing major.

2022-07-19 21:42 UTC, mcdee commented on api/v1/validatorregistration.go
> +	Timestamp    uint64
This should be a `time.Time` (as used in `genesis.go`).

2022-07-19 21:42 UTC, mcdee commented on api/versionedsignedvalidatorregistration.go
> +	Bellatrix *apiv1.SignedValidatorRegistration
This object isn't under the consensus specs versioning (this is stated explicitly in https://github.com/ethereum/builder-specs/blob/main/specs/builder.md#independently-versioned) so should use its own versioning (perhaps `spec.BuilderVersion`)

2022-07-20 06:59 UTC, ciaranmcveigh5 commented on api/v1/validatorregistration_test.go
> +			input: []byte(`{"fee_recipient":"0x000102030405060708090a0b0c0d0e0f10111213","gas_limit":"100","timestamp":"invalid","pubkey":"0x000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202
time.unix() is of type int64 not sure how you want to test for invalid data - for now i've just used "invalid"

2022-07-20 07:01 UTC, ciaranmcveigh5 commented
Thanks for reviewing have made the requested updates, tests are passing - let me know if the builderVersion implementation isn't in line with what you were thinking

2022-07-21 09:56 UTC, mcdee requested changes

2022-07-21 09:56 UTC, mcdee commented on api/versionedvalidatorregistration.go
>  	Bellatrix *apiv1.ValidatorRegistration
This field should map to the builder version, so be called `V1` rather than `Bellatrix`.

2022-07-22 17:57 UTC, mcdee approved these changes

2022-07-22 18:08 UTC, mcdee requested changes

2022-07-22 18:08 UTC, mcdee commented on spec/builderversion.go
> +	return []byte(fmt.Sprintf("%q", responseVersionStrings[*d])), nil
Should be `responseBuilderVersionStrings`

2022-07-22 18:08 UTC, mcdee commented on spec/builderversion.go
> +	if int(d) >= len(responseVersionStrings) {
Should be `responseBuilderVersionStrings`

2022-07-22 18:08 UTC, mcdee commented on spec/builderversion.go
> +	return responseVersionStrings[d]
Should be `responseBuilderVersionStrings`

2022-07-23 11:39 UTC, moshe-blox commented
I have made some changes and successfully tested against Teku on Sepolia, please take a look at https://github.com/ciaranmcveigh5/go-eth2-client/pull/1 if you can.

Hopefully this can get merged to this repo eventually.

2022-07-25 19:45 UTC, mcdee commented
Need to address the above items where `responseVersionStrings` should be `responseBuilderVersionStrings`, apart from that looking good.

2022-07-25 20:41 UTC, ciaranmcveigh5 commented
hey @mcdee I believe the above items where responseVersionStrings should be responseBuilderVersionStrings have been addressed in @moshe-blox commits

currently builderversion.go has `responseBuilderVersionStrings`

and dataversion.go has `responseVersionStrings`

2022-07-25 20:45 UTC, merged